### ISSUE TITLE
Set up a meeting with module coordinator to discuss project trajectory

### ISSUE THREAD

**Issue by davidbenicek** [davidbenicek/raytracer#12]

**Comment by davidbenicek** [comment]
I emailed to set up a meeting - declined.
Emailed again to ask the questions over email, reply as follows (my questions are in `code`):

> Hello
>
>David,
>
>`1.  For the backend, we've found a bunch of tutorials (Ray Tracing from the Ground Up by
>Kevin Suffern) which explains how ray tracing works and walks you through
>how to build a simple ray tracer. I assume we're okay to use resources like
>that`
>
>Yes, provided you document it faithfully.
>
>`2.  For the front end, we're going to take an iterative approach; start
>with a form, then make two 2D views (top-down and side views) and lastly
>create a 3D interface that can be rotated and all. The first two steps
>we're going to do completely ourselves but we were thinking of using a
>library for the 3D view - is that okay or would we get points deducted for
>that? (i.e. we're going to fulfil the basic requirements ourselves but try
>and abstract some of the heavy lifting away with a library for the 3D - is
>there a penalty for that?)`
>
>It's a trade-off. The more you get libraries to do, the harder it is for you
>to show your skills. But, of course, some advanced functionality can (within
>the time constraints of the project) only be achieved by using external
>libraries. Notice: I'm deliberately not committing myself either way here ;)
>You have to make the judgement yourself (and, when you use external
>libraries, faithfully document that you did so).
>
>`3.  We've been following a pretty good process so far both in development
>(which you mentioned will factor into the grades) and also in how we
>operate, run our meetings and document the outcomes of our meetings. For
>example, we're maintaining a wiki to collate our meeting
>notes, designs etc. We're of course going to benefit from doing that when
>we come to writing our report but is that something that you will look at
>during assessment? I'm asking because if you're going to be looking at it
>we'll dedicate time to make it readable and understandable to the
>outside...if not, we'll just dump our notes there in a way that we can read
>but that might not make sense to others...so just wondering if it's worth
>our time to upkeep the presentation and readability of it 😊`
>
>Your internal stuff is your own. Inasmuch as you tell the markers about how
>you went about it, that may play a part in your eventual marking; but we do
>not go out of our way to look at your internal notes.
>
>
>Laurence

**Comment by othmankh** [comment]
That' cool. And it is fair enough. And we'll document everything we use. In addition to that, the use of external libraries will be in complicated situations, which will need more work, that might exceed the time limit, we're currently having. And yes; since no one will go through our notes, we can just demonstrate that in the report, presentation ... etc.
