### ISSUE TITLE
Write the implementation of Util classes

### ISSUE THREAD

**Issue by othmankh** [davidbenicek/raytracer#17]
It is clear from the problem definition, that we need the following classes:
Point3D: which represents the (x,y,z) of the point.
Vector3D: which is also represented by (x,y,z) and which will be used mainly to represent the direction of some ray.
Ray: it will be built from an origin point, and a direction vector.
Light: Each light will have a position, color, and intensity.
Geometry object: it is the abstract class of geometry objects, which will include a method called Intersect, and it is implementation depends on the type of the object. In addition to attribute for the Material of the object.
ColorRGB: this class represents the color in R,G,B values mapped from 0 to 1, and will be perform different operations on colours such as Addition, Subtraction, ... etc.

**Comment by othmankh** [comment]
What remains now to write the implementation of Intersect method for a sphere.

**Comment by davidbenicek** [comment]
Reviewed and merged in https://github.com/davidbenicek/raytracer/pull/18 . Thanks!
