### ISSUE TITLE
Write Unit Tests

### ISSUE THREAD

**Issue by nargy96** [davidbenicek/raytracer#34]
In this task, we need to write the unit tests for all classes in order to satisfy the statement coverage metric.

1. Test the methods in Point3D and Vector3d( Add, Subtract, ... etc).
2. Test the Scene class:
- Create a scene object by using different constructors.
- Test the GetHitInfo Method in its three cases.
- FinalPicture Method.
- DisplayPixel Method.
3. In Tracer:
TraceRay and TraceShade Method -> The TraceRay will call the TraceShade, so testing one will call the other one.

**Comment by davidbenicek** [comment]
So far we've got 3 test classes with 3 tests each. We're extending the definition of done for this issue to be 100% function coverage for critical points in the code - @othmankh will outline exactly what those are in an upcoming comment

**Comment by othmankh** [comment]
There is another issue with the number 65 is just opened, and it outlined everything related to what needs to be tested.

**Comment by othmankh** [comment]
Done from Narg's side
